#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Sensor, dgtl1,  leftPneumatic,  sensorDigitalOut)
#pragma config(Sensor, dgtl12, rightPneumatic, sensorDigitalOut)
#pragma config(Motor,  port1,           frontLeftMotor, tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           backLeftMotor, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           leftArmMotor,  tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           rightArmMotor, tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           GrabberMotor,  tmotorServoStandard, openLoop)
#pragma config(Motor,  port9,           backRightMotor, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          frontRightMotor, tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Varibles.c"
#include "CONTROL_COMMANDS.c"

task main();
{
	while(true)
	{
		DriveChain();
		PressureControl();
	}
}
